# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cloudsecurity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cloudsecurity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63loudsecurity.proto\x12\x05\x63loud\"P\n\x07Request\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x11\n\tfile_size\x18\x04 \x01(\x03\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2\x96\x01\n\x0bUserService\x12(\n\x05login\x12\x0e.cloud.Request\x1a\x0f.cloud.Response\x12-\n\nget_status\x12\x0e.cloud.Request\x1a\x0f.cloud.Response\x12.\n\x0bupload_file\x12\x0e.cloud.Request\x1a\x0f.cloud.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cloudsecurity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=30
  _globals['_REQUEST']._serialized_end=110
  _globals['_RESPONSE']._serialized_start=112
  _globals['_RESPONSE']._serialized_end=138
  _globals['_USERSERVICE']._serialized_start=141
  _globals['_USERSERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
